### ISSUE TITLE
Is this action still valid? 

### ISSUE THREAD

**Issue by jikuma** [jclem/action-github#2]

**Comment by jikuma** [comment]
I was looking for create release action, Finally created my own action for it https://github.com/jikuma/githubaction/releases/tag/v1.0-alpha.

Any plans to update these actions?

**Comment by 63isOK** [comment]
@jclem Is this action still valid?

**Comment by razzeee** [comment]
It only seems to cover issues, can't even comment on pull requests :/

**Comment by jclem** [comment]
I believe it's "valid", but unmaintained, as https://github.com/actions/github-script is a much better replacement. I think it should be archived (but left available, as I'm not sure if people are using it).
